### PR TITLE
Small changes for the delete confirmation modal and create new folder button

### PR DESCRIPTION
**Pull request by katieki**
adjusted the confirm delete modal to look better (shortened the gap between the yes/no buttons)
added button animations and dark mode css styling to match the rest of the buttons to the yes/no buttons and create button in the create new folder modal

### CODE REVIEW

**Review by pviwatkurkul — COMMENTED** [review]
Should be some very simple merge conflict handling, most of it is from JSDocs having replacing their own lines. Otherwise check through merge conflicts of the actual files we edit please and thank you!

**Comment by pviwatkurkul** [comment]
can you also fix some linting errors please, just do it locally, as I dont exactly know why it's not running on this PR

**Comment by katieki** [comment]
for some reason gwen was having this issue during the last iteration too but the linting wasnt working for us locally TT it kept making us download npx when we alr had it installed and no other solutions

**Review by anshisinghh — APPROVED** [review]

**Review by pviwatkurkul — APPROVED** [review]
Looks great thanks

**Pull request merged**
