### PR TITLE
Update task.html

### PR DESCRIPTION
**Pull request by PussakornCH**
add button on HTML

### CODE REVIEW

**Comment by anshisinghh** [comment]
new note and new folder buttons should be on home page not task list

**Comment by pviwatkurkul** [comment]
can you add two reviewers not one

**Comment by pviwatkurkul** [comment]
also please manually pull most recent changes from main first

**Review by anshisinghh — CHANGES_REQUESTED** [review]
new note and new folder buttons should go on home not task list

**Review by anshisinghh — CHANGES_REQUESTED** [review]
code looks great but can you look through and fix some of the linting errors for CSS and JS

**Comment by pviwatkurkul** [comment]
See Slack message about updating Linting files. Also lint the codebase to the best of your ability.

**Pull request closed without merging**
