### PR TITLE
Create Embed_code

### PR DESCRIPTION
**Pull request by PussakornCH**

### CODE REVIEW

**Review by anshisinghh — CHANGES_REQUESTED** [review]
i thought we were only using one font?

**Comment by PussakornCH** [comment]
I delete the other fonts that we don't use and change Embed_code to md file

**Comment by pviwatkurkul** [comment]
What is the .md file for?

**Comment by PussakornCH** [comment]
.md - I first thought that I would include the Google font embed code.
I delete Embed_code.md because the Google font code is already included in the index.html file and it did not pass the test.

**Pull request closed without merging**
